### ISSUE TITLE
Create the Data Catalog

### ISSUE THREAD

**Issue by rodrigoalvamat** [dappmesh/dappmesh#38]
### Overview

*As a* DappMesh developer, I want to define the data product schemas, data flows, and data contracts declaratively *so that* the Data Catalog service can provide federated governance at the cluster level.

### Requirements

- [ ] Create Data Catalog CRDs
- [ ] Create mesh operator's controller to Data Catalog API
- [ ] Create Data Catalog gRPC service
- [ ] Create Data Catalog sample application

### Related issues

- #

### Design and documentation reference

**Reference Implementation:** [Unity Catalog OS](https://github.com/unitycatalog/unitycatalog/)
