### ISSUE TITLE
Data Application CLI

### ISSUE THREAD

**Issue by rodrigoalvamat** [dappmesh/dappmesh#43]
### Overview

_As_ a DappMesh developer, _I want_ to use a command line interface _so that_ I can install the platform requirements, bootstrap a data product project, and create, update, delete, and query resources.

### Requirements

- [ ] Define commands to install DappMesh platform requirements in Linux, Mac, and Win
- [ ] Define commands to bootstrap a data product project
- [ ] Define commands to create DappMesh resources
- [ ] Define commands to delete DappMesh resources
- [ ] Define commands to update DappMesh resources
- [ ] Define commands to query DappMesh resources

### Related issues

- #

### Design and documentation reference

**Parser:** [Clap](https://docs.rs/clap/latest/clap/)
